# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Documents\GitHub\Music-Recommendation-System\PythonApp\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(594, 692)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(594, 692))
        Form.setMaximumSize(QtCore.QSize(594, 692))
        self.label0 = QtWidgets.QLabel(Form)
        self.label0.setGeometry(QtCore.QRect(440, 10, 111, 16))
        self.label0.setObjectName("label0")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 410, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 100, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(80, 450, 451, 201))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(80, 270, 451, 121))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 450, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(90, 240, 141, 16))
        self.label_4.setObjectName("label_4")
        self.radioButton_happy = QtWidgets.QRadioButton(Form)
        self.radioButton_happy.setGeometry(QtCore.QRect(90, 140, 81, 71))
        self.radioButton_happy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\pc\\Documents\\GitHub\\Music-Recommendation-System\\PythonApp\\icons/happy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_happy.setIcon(icon)
        self.radioButton_happy.setIconSize(QtCore.QSize(64, 64))
        self.radioButton_happy.setObjectName("radioButton_happy")
        self.radioButton_sad = QtWidgets.QRadioButton(Form)
        self.radioButton_sad.setGeometry(QtCore.QRect(180, 140, 81, 71))
        self.radioButton_sad.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\pc\\Documents\\GitHub\\Music-Recommendation-System\\PythonApp\\icons/sad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_sad.setIcon(icon1)
        self.radioButton_sad.setIconSize(QtCore.QSize(64, 64))
        self.radioButton_sad.setObjectName("radioButton_sad")
        self.radioButton_inlove = QtWidgets.QRadioButton(Form)
        self.radioButton_inlove.setGeometry(QtCore.QRect(270, 140, 81, 71))
        self.radioButton_inlove.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\pc\\Documents\\GitHub\\Music-Recommendation-System\\PythonApp\\icons/inlove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_inlove.setIcon(icon2)
        self.radioButton_inlove.setIconSize(QtCore.QSize(64, 64))
        self.radioButton_inlove.setObjectName("radioButton_inlove")
        self.radioButton_angry = QtWidgets.QRadioButton(Form)
        self.radioButton_angry.setGeometry(QtCore.QRect(360, 140, 81, 71))
        self.radioButton_angry.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\pc\\Documents\\GitHub\\Music-Recommendation-System\\PythonApp\\icons/angry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_angry.setIcon(icon3)
        self.radioButton_angry.setIconSize(QtCore.QSize(64, 64))
        self.radioButton_angry.setObjectName("radioButton_angry")
        self.radioButton_fear = QtWidgets.QRadioButton(Form)
        self.radioButton_fear.setGeometry(QtCore.QRect(450, 140, 81, 71))
        self.radioButton_fear.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\pc\\Documents\\GitHub\\Music-Recommendation-System\\PythonApp\\icons/fear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_fear.setIcon(icon4)
        self.radioButton_fear.setIconSize(QtCore.QSize(64, 64))
        self.radioButton_fear.setObjectName("radioButton_fear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Music Recommendation System"))
        self.label0.setText(_translate("Form", "Work in process.."))
        self.pushButton.setText(_translate("Form", "Create Playlist"))
        self.label.setText(_translate("Form", "How do you feel?"))
        self.label_2.setText(_translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n"
"Proin ut orci non lorem gravida sollicitudin.\n"
"Ut feugiat mi eu viverra molestie.\n"
"Duis ultricies nulla vel porta vehicula.\n"
"Etiam venenatis augue quis orci suscipit viverra.\n"
"Vestibulum ut turpis sagittis, commodo ante at, faucibus tellus.\n"
"Fusce convallis risus quis justo tempor, id ullamcorper nisl interdum.\n"
"Donec eget neque mattis, blandit erat quis, vestibulum sapien.\n"
"Sed sed urna non felis fringilla commodo.\n"
"In in lectus gravida, rutrum nulla id, porttitor lorem."))
        self.plainTextEdit.setPlainText(_translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n"
"Proin ut orci non lorem gravida sollicitudin.\n"
"Ut feugiat mi eu viverra molestie.\n"
"Duis ultricies nulla vel porta vehicula.\n"
"Etiam venenatis augue quis orci suscipit viverra."))
        self.label_3.setText(_translate("Form", "Recommended songs"))
        self.label_4.setText(_translate("Form", "What\'s your favorite musics?"))
